name: Enviar Entrega al Repositorio de Evaluación

on:
  # Cambiamos 'pull_request' por 'pull_request_target' para desbloquear los secretos de forma segura
  pull_request_target:
    branches:
      - develop
    types: [opened, synchronize]

jobs:
  copy-to-prof-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v4
        with:
          # Esto asegura que descargue el código que el alumno está enviando en el PR
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0

      - name: Configurar Git
        run: |
          git config --global user.name "Evaluador Automático"
          git config --global user.email "evaluador@universidad.edu"

      - name: Empujar rama y crear PR en repositorio privado
        env:
          FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: "true"
          TOKEN: ${{ secrets.PROFE_GITHUB_TOKEN }}
          REPO_DESTINO: "jgotuniversidad/2026-2-project-responses"
          ALUMNO: ${{ github.event.pull_request.user.login }}
          URL_ORIGINAL: ${{ github.event.pull_request.html_url }}
        run: |
          RAMA_LOCAL="entrega-${ALUMNO}"
          
          # 1. Autenticar la herramienta CLI de GitHub
          echo "${TOKEN}" | gh auth login --with-token
          
          # 2. Configurar la URL remota usando el protocolo HTTPS autenticado
          REMOTE_URL="https://x-access-token:${TOKEN}@github.com/${REPO_DESTINO}.git"
          
          # 3. Conectar y empujar al repositorio destino privado
          git remote add destino "$REMOTE_URL"
          git push -f destino HEAD:refs/heads/${RAMA_LOCAL}
          
          # 4. Crear el Pull Request en el repositorio privado del profesor
          gh pr create \
            --repo "${REPO_DESTINO}" \
            --head "${RAMA_LOCAL}" \
            --base "develop" \
            --title "Entrega de: ${ALUMNO}" \
            --body "Código enviado automáticamente. PR Original: ${URL_ORIGINAL}" || echo "La rama ha sido actualizada en el repositorio privado."